name: easy-openvpn
version: 0
summary: An easy-to-manage OpenVPN deployment.
description: |
    OpenVPN snap with management scripts that simplify PKI and client
    management for fast, cheap and disposable VPNs. Based on
    https://github.com/kylemanna/docker-openvpn.
confinement: strict

apps:
    easy-openvpn:
        command: bin/ovpn_run
        daemon: simple
        plugs:
            - network
            - network-bind
            - network-control
            - firewall-control
    genconfig:
        command: bin/ovpn_genconfig
    initpki:
        command: bin/ovpn_initpki
    list-clients:
        command: bin/ovpn_listclients
    get-client:
        command: bin/ovpn_getclient
    status:
        command: bin/ovpn_status

parts:
    packages:
        plugin: nil
        stage-packages:
            - openvpn
            - openssl
            - iptables
    easyrsa:
        plugin: dump
        source: https://github.com/OpenVPN/easy-rsa/releases/download/3.0.1/EasyRSA-3.0.1.tgz
        organize:
            easyrsa: usr/local/easyrsa/easyrsa
            openssl-1.0.cnf: usr/local/easyrsa/openssl-1.0.cnf
            x509-types: usr/local/easyrsa/x509-types
        snap:
            - usr/local/easyrsa
    scripts:
        plugin: dump
        source: .
        snap:
            - bin/*
